[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.219"
serde_json = "1.0.141"
zbus = "5.9.0"
zvariant = { version = "5.6.0", features = ["chrono"] }
tokio = { version = "1", features = ["full"] }
chrono = { version = "0.4.42", features = ["clock", "serde"] }
